SitePen/remap-istanbul

lib/remap.js

The current define detection is invalid because by declaring `var define`, the top-level `define` in scope will always be undefined.
This adjustment should align the original intention I believe, but let me know if I'm missing anything here.

Properly scope AMD define

---

lib/remap.js

This re-uses the same exclude regex to remove files after mapping back.
There are obviously ways to improve performance here, but this at least works correctly.

exclude files from the output

---

lib/gulpRemapIstanbul.js

for our project we have a mix of js and typescript.  your plugin works great except I know people will complain about the warn messages.  I saw this as an easy way to get rid of those warn messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sitepen/remap-istanbul/56)

allow for warn option to be user specified

---

lib/remap.js
tests/unit/lib/remap.js

Currently, `remap-istanbul` gracefully handles non-existent inlined sourcemaps, but throws fatal error for non-existent external sourcemap files. This pr fixes that. Issue depicted [here](https://github.com/CanopyTax/node-jspm-jasmine/pull/27#issuecomment-220664578).

Graceful handling of invalid/non-existent sourceMappingURL

---

lib/remap.js
tests/unit/lib/remap.js

Added source code as an array to fileCoverage object so that istanbul html reporter doesn't throw error
Error: Unable to find entry for [x]

fix(remap) Added source code as an array to fileCoverage object.

---

lib/remap.js

If the node version is below 0.12, the WeakMap implementation is not available. This patch enebles remap to run in older node environments.

stop using WeakMap when not available

---

README.md

Use [david-dm](https://david-dm.org/SitePen/remap-istanbul) to monitor the status of the dependencies.

Add dependency status to README

---

lib/remap.js

This fixes an issue where `undefined` is being passed to `path.extname` and then having `path` error.
I produced the above sceneraio by having a typescript file export only an interface. When the file was compiled by typescript it no longer had any content and I belive that caused the aforementioned error. Placing a single comment or var statement in the file stopped this error from occuring.
The stacktrace I received is included below.
```
TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.extname (path.js:887:5)
at $PWD/node_modules/remap-istanbul/lib/remap.js:291:37
at Array.forEach (native)
at $PWD/node_modules/remap-istanbul/lib/remap.js:214:22
at Array.forEach (native)
at remap ($PWD/node_modules/remap-istanbul/lib/remap.js:213:12)
at …
```

fixed: "path.extname" error in remap.js

---

src/CoverageTransformer.js

When locating the source map, use the source map included in the file coverage whenever possible. Closes #2 but requires istanbuljs/istanbul-lib-instrument#23

Consider embedded input source map in file coverage

---

README.md

Running against node.js version 4 results in this error:
```
node_modules/remap-istanbul/bin/remap-istanbul.js:19
let buffer = '';
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:990:3```

updated supported node.js version in docs

---

src/CoverageTransformer.js

This PR: https://github.com/SitePen/remap-istanbul/pull/65 introduced a bug that would overwrite the sources array and lead to issues like this: https://github.com/marcules/karma-remap-istanbul/issues/31 
My workaround is to only apply this fix if there is only 1 source - however this is probably completely the wrong way to resolve this - any guidance would be greatly appreciated 😃

fix: dont overwrite sources array

---

package.json
src/checkThreshold.js
src/gulpRemapIstanbul.js

Adds the ability to pass a check option from the gulp plugin to require a certain coverage threshold or fail the gulp command.
The syntax and implementation are ported from the karma-coverage test runner (https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check).
usage looks like: 
```
return gulp.src('tests/coverage/coverage-final.json')
.pipe(remapIstanbul({
check: {
global: {
statements: 50,
branches: 50,
functions: 50,
lines: 50,
excludes: [
'foo/bar/**/*.js'
]
},
each: {
statements: 50,
branches: 50,
functions: 50,
lines: 50,
excludes: [
'other/directory/**/*.js'
],
overrides: {
'baz/component/**/*.js': {
statements: 98
}
}
}            
},
reports: {
'html': 'tests/coverage/html-report',
'cobertura': 'tests/coverage/cobertura-coverage.xml',
'json': …
```

fix for issue #61

---

README.md
src/CoverageTransformer.js
src/remap.js
tests/unit/lib/remap.js

This PR provides the ability to pass a option named `mapFileName` to the `remap()` function, which is a function which takes the remapped filename as a string and returns a string which represents the final filename which should be added to the remapped coverage.
This makes it possible to *unmangle* filenames that are potentially mangled by bundlers and would support "rebasing" of files in the remapped coverage.
Fixes #143

Add support for remapping filenames

---

src/CoverageTransformer.js
tests/unit/lib/remap.js

This fixes and issue where if a store of sources was passed to `remap()` and the filenames were remapped, the corresponding change was not made in the source store.

Also remap sources when remapping filenames

---

src/CoverageTransformer.js

When a basePath is specified, if the origFileName is undefined, the program errors out when executing the replace() method.

Checking if 'origFileName' is defined before using it to build a file path

---

src/CoverageTransformer.js
src/gruntRemapIstanbul.js

Previously, there was no way to suppress these errors when a source map could not be found:
```
>> Error: Could not find source map for: "app/src/blah.js"
```
For projects that are in the process of migrating to TypeScript, not all files will have corresponding source maps.
This adds a `warnMissingSourceMaps` parameter (defaults to `true` to keep existing behavior) which can be used to suppress these errors.

Add warnMissingSourceMaps parameter

---

bin/remap-istanbul.js
tests/unit/bin/remap-istanbul.js

This change allows specifying '-o null' to specify that the filename should
be set to null. Doing so allows the reports such as 'text-summary' to be
printed to console instead of a file.

Allow null file name

---

package.json

prevent pulling in source-map 0.7.0 by pinning to 0.6.X

Lock down version of source-map ^0.6.1

---

src/CoverageTransformer.js

This is a fix for #150. See my review there.
Just fixing the logic for setting the instance `warnMissingSourceMaps` property - we want to allow falsy values from `options`.

Fix warnMissingSourceMaps always set to true

---

src/CoverageTransformer.js

Some tools, like Closure Compiler, produce source maps that are not base64 encoded, but are instead just URL encoded.
This PR updates the regex to look for either base64 encoded or url encoded source maps, and parses each appropriately.

Support url encoded sourcemaps.

---

src/CoverageTransformer.js

There are some projects which have an `extname` on its project name. According the results of the query from npmjs.com... - https://www.npmjs.com/search?q=.js
* https://www.npmjs.com/package/popper.js
* https://www.npmjs.com/package/big.js
* https://www.npmjs.com/package/hash.js
* https://www.npmjs.com/package/reveal.js
Let's say that we are making a project named abc.js on TypeScript; We are building something on the directory like below,
```bash
/Users/heycalmdown/development/abc.js$ npm run lcov-remap
```
The `coverage/lcov.info` will start with 
```
TN:
SF:/Users/heycalmdown/development/abc.js/dist/index.js
```
And the remap file starts with
```
TN:
SF:/Users/heycalmdown/development/abc.ts/dist/index.js
```
Expected result is
```
TN: …
```

fix: path replace fail when dirname has same ext

---

package-lock.json
package.json
tests/unit/lib/gulpRemapIstanbul.js

This PR updates Gulp to v4 in `devDependencies`. Gulp 4 was released a year ago and Gulp 3.9.1 is almost 3 years old.
No changes to the core `remap-istanbul` code were required; only the Gulp unit tests have been updated.
This effort brings `remap-istanbul` more up-to-date with the JS ecosystem and reduces dependencies on vulnerable 3rd-party libraries.

Upgrade to Gulp 4

---

.gitignore
package-lock.json
package.json
tests/intern.json
tests/run_ci.sh

[`codecov.io`](https://github.com/cainus/codecov.io) has been superseded by [`codecov-node`](https://github.com/codecov/codecov-node), but in any case the [bash script](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) is the preferred approach.
This PR:
* Removes [`codecov.io`](https://github.com/cainus/codecov.io) from `devDependencies` (which also reduces vulnerable dependencies to zero!)
* Uses the codecov.io [bash script](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) in the CI script
* Adds coverage configuration to the Intern config
It has been [tested and confirmed](https://codecov.io/gh/SitePen/remap-istanbul/commit/162baf40c769bf8fc63dd225f63bb5efb6b80c20) to upload coverage information to https://codecov.io/
After merging this should restore …

Update code coverage configuration
